apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-config.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "cloud-config.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "cloud-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "cloud-config.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.springProfilesActive | quote }}
            - name: SPRING_ZIPKIN_BASE_URL
              value: {{ .Values.env.springZipkinBaseUrl | quote }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.env.eurekaClientServiceUrlDefaultZone | quote }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START
              value: {{ .Values.env.springCloudConfigServerGitCloneOnStart | quote }}
          {{ if .Values.probes.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.probes.liveness.port }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{ end }}
          {{ if .Values.probes.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.probes.readiness.port }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{ end }}

          {{ if .Values.resources }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          {{ end }}
