apiVersion: v2
name: favourite-service
description: A Helm chart for Favourite Service microservice
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - microservice
  - favourite-service
  - ecommerce
maintainers:
  - name: Ecommerce Team
