apiVersion: v2
name: grafana
description: A Helm chart for Grafana dashboards
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - monitoring
  - grafana
  - dashboards
maintainers:
  - name: Ecommerce Team

