apiVersion: v1
kind: Service
metadata:
  name: {{ include "favourite-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "favourite-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{ if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
  selector:
    {{ include "favourite-service.selectorLabels" . | nindent 4 }}
