apiVersion: v2
name: payment-service
description: A Helm chart for Payment Service microservice
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - microservice
  - payment-service
  - ecommerce
maintainers:
  - name: Ecommerce Team
