---
- name: Configurar VM App (microservicios)
  hosts: app_vm
  become: true
  vars:
    app_dir: "/opt/ecommerce"
    repo_src: "."
  roles:
    - role: docker
    - role: microservices

- name: Configurar VM CI (k3s + Helm + Jenkins + SonarQube + Trivy)
  hosts: ci_vm
  become: true
  roles:
    - role: ci_stack

