apiVersion: v2
name: shipping-service
description: A Helm chart for Shipping Service microservice
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - microservice
  - shipping-service
  - ecommerce
maintainers:
  - name: Ecommerce Team
