apiVersion: v2
name: api-gateway
description: A Helm chart for Api Gateway
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - api-gateway
  - ecommerce
maintainers:
  - name: Ecommerce Team
